# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# run from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/analysis_options.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # treat missing required parameters as a fatal error
    missing_required_param: error
    # treat missing returns as a fatal error
    missing_return: error
    # treat undefined named parameters as a fatal error
    undefined_named_parameter: error
    # allow having todos in the code
    todo: ignore

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable existing rules from the `package:flutter_lints/analysis_options.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: <lint_rule>` and
  # `// ignore_for_file: <lint_rule>` syntax on the line or in the file
  # producing the lint.
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - use_key_in_widget_constructors
