class Materi {
  final String id;
  final String? orgId;
  final String tanggal;
  final List<String>? guru;
  final String isi;
  final DateTime? createdAt;

  Materi({
    required this.id,
    this.orgId,
    required this.tanggal,
    this.guru,
    required this.isi,
    this.createdAt,
  });

  factory Materi.fromJson(Map<String, dynamic> json) {
    return Materi(
      id: json['id'] as String,
      orgId: json['org_id'] as String?,
      tanggal: json['tanggal'] as String,
      guru: (json['guru'] as List<dynamic>?)?.map((e) => e as String).toList(),
      isi: json['isi'] as String,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String).toLocal()
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // Usually generated by DB or Service
      'org_id': orgId,
      'tanggal': tanggal,
      'guru': guru,
      'isi': isi,
      // 'created_at': createdAt, // Managed by DB
    };
  }
}
